fix: Выполнить спринт-13.
EvgeniiVarlakhov/java-shareit pull request #1
Opened 2022-10-06 08:31 UTC by EvgeniiVarlakhov

Выполнено заданий спринт-13.

2022-10-07 06:49 UTC, kukolev requested changes

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>   * TODO Sprint add-bookings.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * TODO Sprint add-controllers.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * TODO Sprint add-controllers.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>   * TODO Sprint add-controllers.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void userValidate(long userId) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>   * TODO Sprint add-item-requests.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserController.java
>   * TODO Sprint add-controllers.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/model/User.java
> + * TODO Sprint add-controllers.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Email(message = "Email имеет не правельный формат.", groups = {CreateUser.class, UpdateUser.class})
Орфографические ошибки в слове «неправильный». Нужно исправить.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/exception/InvalidValidationException.java
> +    public InvalidValidationException(String string) {
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/exception/ObjectNotFoundException.java
> +    public ObjectNotFoundException(String string) {
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-10-07 06:49 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public Collection<ItemDto> getAllItem(long userId) {
По моему здесь не хватает «s» в названии метода = `getAllItems `было бы корректней.

2022-10-07 08:20 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>   * TODO Sprint add-bookings.
Выполнено.

2022-10-07 08:22 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * TODO Sprint add-controllers.
Выполнено.

2022-10-07 08:22 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * TODO Sprint add-controllers.
Выполнено.

2022-10-07 08:22 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>   * TODO Sprint add-controllers.
Выполнено.

2022-10-07 08:26 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void userValidate(long userId) {
Название метода изменено.

2022-10-07 08:27 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>   * TODO Sprint add-item-requests.
Выполнено.

2022-10-07 08:28 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/user/UserController.java
>   * TODO Sprint add-controllers.
Выполнено.

2022-10-07 08:28 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/user/model/User.java
> + * TODO Sprint add-controllers.
Выполнено.

2022-10-07 08:29 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Email(message = "Email имеет не правельный формат.", groups = {CreateUser.class, UpdateUser.class})
Исправлено.

2022-10-07 08:32 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/exception/InvalidValidationException.java
> +    public InvalidValidationException(String string) {
Исправлено.

2022-10-07 08:32 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/exception/ObjectNotFoundException.java
> +    public ObjectNotFoundException(String string) {
Исправлено.

2022-10-07 08:33 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public Collection<ItemDto> getAllItem(long userId) {
Исправлено.

2022-10-07 15:34 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Email(message = "Email имеет неправельный формат.", groups = {CreateUser.class, UpdateUser.class})
Орфографическая ошибка в слове «неправильный». Нужно исправить.

2022-10-07 15:34 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Email(message = "Email имеет не правельный формат.", groups = {CreateUser.class, UpdateUser.class})
Исправлена только одна ошибка. Нужно исправить вторую.

2022-10-08 08:26 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Email(message = "Email имеет неправельный формат.", groups = {CreateUser.class, UpdateUser.class})
исправлено)

2022-10-08 23:59 UTC, kukolev approved these changes

2022-10-09 07:19 UTC, merged