fix - выполнить спринт -14.
EvgeniiVarlakhov/java-shareit pull request #2
Opened 2022-10-28 05:18 UTC by EvgeniiVarlakhov

Выполнить спринт 14

2022-10-28 16:30 UTC, kukolev requested changes

2022-10-28 16:30 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        try {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать. Код при этом может выглядеть примерно так:

```
public SomeResult someMethod(...) {
    validateSomething(...);
    // business-logic here
}

private void validateSomething(...) {
    if (/* ! check something /*) {
        throw new SomeException();
    }
}

```

Таким образом в методе someMethod визуально будет проще найти бизнес-логику, ради которой этот метод и создавался.

2022-10-28 16:30 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        try {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать. Код при этом может выглядеть примерно так:

```
public SomeResult someMethod(...) {
    validateSomething(...);
    // business-logic here
}

private void validateSomething(...) {
    if (/* ! check something /*) {
        throw new SomeException();
    }
}

```

Таким образом в методе someMethod визуально будет проще найти бизнес-логику, ради которой этот метод и создавался.

2022-10-28 16:30 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        try {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать. Код при этом может выглядеть примерно так:

```
public SomeResult someMethod(...) {
    validateSomething(...);
    // business-logic here
}

private void validateSomething(...) {
    if (/* ! check something /*) {
        throw new SomeException();
    }
}

```

Таким образом в методе someMethod визуально будет проще найти бизнес-логику, ради которой этот метод и создавался.

2022-10-28 16:30 UTC, kukolev commented on pom.xml
> +		<dependency>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-28 16:30 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dto/CommentDtoIn.java
> +    @NotBlank(message = "Кооментарий не может быть пустым")
Орфографическая ошибка в слове «Комментарий ». Нужно исправить.

2022-10-30 12:22 UTC, EvgeniiVarlakhov commented on pom.xml
> +		<dependency>
Исправлено.

2022-10-30 12:23 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/item/dto/CommentDtoIn.java
> +    @NotBlank(message = "Кооментарий не может быть пустым")
Исправлено.

2022-10-30 12:56 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        try {
Выполнено. Добавлен приватный метод validateBookingState.

2022-10-30 12:56 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        try {
Выполнено. Добавлен приватный метод validateBookingState.****

2022-10-30 13:08 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        try {
Выполнено. Добавлен приватный метод validateUsersEmail;

2022-10-30 13:32 UTC, EvgeniiVarlakhov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        try {
Изменено на метод validateUserDto.  Попытка проверки через запрос Пользователя по базе через email,  не позволяет пройти тесты Postman, т.к. требуется попытка сохранения в базу, для того, чтобы поменялся счетчик номеров ID.

2022-10-30 18:04 UTC, kukolev approved these changes

2022-12-26 07:47 UTC, merged